### ISSUE TITLE
Unable to upload RAML file from local machine

### ISSUE THREAD

**Issue by DavidJFowler** [mulesoft-labs/raml-dotnet-tools#237] opened 2019-12-20 10:31 UTC
I created a new .net core console app in VS 2019.
Clicked Add RAML/OAS reference
Selected raml file

Got this error message:

Error while parsing raml file. amf.core.remote.FileNotFound: File Not Found: ENOENT: no such file or directory, open 'D:\Users\xxx xxxx\AppData\Local\Temp\tmp4B7B.raml'

The temp file was created in my temp folder on drive C: but the extension appears to be trying to find it on D:

Version 3.0.0
VS 16.4.2
Windows 10 Pro 1903

**Comment by woodp** [comment] 2020-01-02 15:59
I'm unable to reproduce this.
Drive is not harcoded on the code. I'm using "Path.GetTempPath()", that should be consistent and always point to the same drive. So not sure where the problem is.

**Comment by DavidJFowler** [comment] 2020-01-02 16:22
Thanks for the reply. I updated to the latest version of the tool today (3.0.1) and now it just hangs when I attempt to upload a raml file from my local drive.

[System.Io.Path]::GetTempPath() returns the correct temp folder on drive C: note that there is a space in the path name - could that be an issue?

Anyway, tool appears to be completely broken now.

**Comment by woodp** [comment] 2020-01-21 19:21
duplicate of #240, fixed in latest release

**Closed by woodp** 2020-01-21 19:21 UTC
Labels: duplicate
