### ISSUE TITLE
A string array property is incorrectly generated

### ISSUE THREAD

**Issue by StefH** [mulesoft-labs/raml-dotnet-tools#171] opened 2017-08-30 10:15 UTC
RAML is like:

```js
MainObject:
    type: object
    properties:
      mylist:
        type: string[]
        required: true
```

Generated code is like:
```c#
public partial class  MainObject
{

    [JsonProperty("mylist")]
    public string Mylist{ get; set; }

} // end class
```

But is should be:
```c#
public partial class  MainObject
{

    [JsonProperty("mylist")]
    public IList<string> Mylist{ get; set; }

} // end class
```

**Comment by StefH** [comment] 2017-10-11 19:01
Any update?

**Comment by woodp** [comment] 2017-10-13 12:34
Duplicate of https://github.com/mulesoft-labs/raml-dotnet-tools/issues/145

**Closed by woodp** 2017-10-13 12:34 UTC
Labels: duplicate
