### ISSUE TITLE
Access is denied on RAML update/import

### ISSUE THREAD

**Issue by tb-wwparker** [mulesoft-labs/raml-dotnet-tools#126] opened 2017-02-01 18:14 UTC
I have several RAML API references in my project. I updated one of the RAML files and selected update RAML and it said: Error while parsing raml file. Access to the path \\Fileserver\QA\RAML is denied. 

I deleted the reference and then readded it. I was was able to navigate to the RAML file using the Windows file picker (the file is readable), but it throw the same error: Error while parsing raml file. Access to the path \\Fileserver\QA\RAML is denied. 

Why would the parse not have read access? The files are readable/writable by my user account.

**Comment by woodp** [comment] 2017-02-01 18:49
Yes, I've reproduced this error, this is actually a duplicate of #121

**Closed by woodp** 2017-02-01 18:49 UTC
Labels: duplicate
