### ISSUE TITLE
"Enable RAML metadata output - ASP NET CORE WEB API:  option does  not show

### ISSUE THREAD

**Issue by KusumSitecore** [mulesoft-labs/raml-dotnet-tools#139] opened 2017-04-04 11:19 UTC
I am trying to generate RAML file from my web api core application in Visual studio in 2015. I have installed 'RAML Tools for .NET' from the below link.
https://visualstudiogallery.msdn.microsoft.com/cadcb820-762c-4514-9817-884b7558aaa9/view/Discussions
Still I am not able to get the option "Enable RAML metadata output". Any suggestion would be appreciated.

**Comment by woodp** [comment] 2017-04-04 12:20
It will be available in next release

Closing because is a duplicate of https://github.com/mulesoft-labs/raml-dotnet-tools/issues/98

**Closed by woodp** 2017-04-04 12:20 UTC
Labels: duplicate
