### ISSUE TITLE
String array properties not generated #111 is not fixed

### ISSUE THREAD

**Issue by dbelchenko** [mulesoft-labs/raml-dotnet-tools#153] opened 2017-05-15 01:32 UTC
Release 2.0.6 notes says that issue #111 is fixed.
However the tool generates type `string` instead of `IList<string>.`

CopyRecipientEmail?: string[] 
generates to
public string CopyRecipientEmail { get; set; }

**Comment by woodp** [comment] 2017-05-17 13:36
111 is a different issue
this is a duplicate of https://github.com/mulesoft-labs/raml-dotnet-tools/issues/145

**Closed by woodp** 2017-05-17 13:36 UTC
Labels: duplicate
