### ISSUE TITLE
Error importing simple RAML 1.0 definition

### ISSUE THREAD

**Issue by hu3b1129** [mulesoft-labs/raml-dotnet-tools#176] opened 2017-11-29 09:10 UTC
I've a Visual Studio 2015 (Community Edition) with installed RAML Tools for .NET (version 2.1.0). In my WPF Application project I was trying to add RAML Reference (by Upload RAML definition file from my local filesystem that uses a RAML library with ENUM definition) and I get the following error message:

error: Compiling transformation: The name 'apiEnumValues' does not exist in the current context. Line: 1081 Column 26

Do you have an idea what am I doing wrong?

**Comment by hu3b1129** [comment] 2017-11-29 09:15
Here are my RAML files I was working with: 
[raml.zip](https://github.com/mulesoft-labs/raml-dotnet-tools/files/1513147/raml.zip)

**Comment by eduardo-rubio** [comment] 2017-12-01 19:01
It looks similar than #175

**Comment by gdearth** [comment] 2017-12-01 21:40
This and #175 are related, In the RAMLClient.t4 there are references to `apiEnumValues`, this should be `apiEnum.Values`. As a work around, until this is fixed, you can find the file both in the project folder under API References\Templates or in the plugin folder using this PowerShell script `Get-ChildItem -File -Filter "RAMLClient.t4" -Path "$env:LOCALAPPDATA\Microsoft\VisualStudio\14.0\Extensions" -Recurse`.

**Comment by hu3b1129** [comment] 2017-12-04 08:20
Hello,

thanks for your reply. The proposed workaround works properly and I could import my RAML 1.0 into Visual Studio properly :-)

Cheers,
Peter

**Comment by woodp** [comment] 2017-12-21 13:06
duplicate of https://github.com/mulesoft-labs/raml-dotnet-tools/issues/176

**Closed by woodp** 2017-12-21 13:06 UTC
Labels: duplicate
