### ISSUE TITLE
Error with Existing Web API and RAML.

### ISSUE THREAD

**Issue by johncmckim** [mulesoft-labs/raml-dotnet-tools#21] opened 2015-07-28 07:25 UTC
I installed the RAML extension and Enabled metadata output.

However, I am receiving the error below.

````
[ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length]
   System.String.Substring(Int32 startIndex, Int32 length) +14138880
   RAML.WebApiExplorer.SchemaBuilder.HandleNestedTypeProperty(Int32 pad, PropertyInfo prop, String schema, IEnumerable`1 props) +1082
   RAML.WebApiExplorer.SchemaBuilder.GetProperty(Int32 pad, PropertyInfo prop, String schema, IEnumerable`1 props) +309
   RAML.WebApiExplorer.SchemaBuilder.GetProperties(Type elementType, Int32 pad) +353
   RAML.WebApiExplorer.SchemaBuilder.GetMainObjectSchema(Type type) +195
   RAML.WebApiExplorer.SchemaBuilder.Get(Type type) +892
   RAML.WebApiExplorer.ApiExplorerService.AddSchema(Type type) +177
   RAML.WebApiExplorer.ApiExplorerService.GetResponses(ResponseDescription responseDescription) +470
   RAML.WebApiExplorer.ApiExplorerService.GetMethods(ApiDescription api, ICollection`1 verbs) +658
   RAML.WebApiExplorer.ApiExplorerService.AddMethods(Resource resource, ApiDescription api, ICollection`1 verbs) +131
   RAML.WebApiExplorer.ApiExplorerService.GetRaml(String title) +2287
   RAML.WebApiExplorer.RamlController.GetRamlContents() in C:\Users\John\Development\CareerHub\Applications\CareerHub\Web\Controllers\RamlController.cs:32
   RAML.WebApiExplorer.RamlController.Raw() in C:\Users\John\Development\CareerHub\Applications\CareerHub\Web\Controllers\RamlController.cs:17
   lambda_method(Closure , ControllerBase , Object[] ) +87
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +229
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +35
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +39
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +67
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +72
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +38
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +186
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +44
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +399
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +157
````

After looking at the source I found in https://github.com/mulesoft-labs/raml-dotnet-tools/blob/master/Raml.WebApiExplorer/RAML.WebApiExplorer/SchemaBuilder.cs the if statement in the `GetProperty` Method is not indented correctly. I suspect `HandleNestedTypeProperty` is being called when is should not be called.

**Comment by woodp** [comment] 2015-07-29 15:36
HandleNestedTypeProperty is the right method to be called.

The problem is that it's failing to convert one of your objects to a json schema.  But I don't have enough info to work with.
Could you please provide a minimum WebAPI in which it fails ?

**Comment by johncmckim** [comment] 2015-07-30 01:15
I'm running this on a large existing Web API. I'll try to identify the problem area and get back to you. Do you have any suggestions for identifying it?

I think I will have to clone the project and run it in a debugger to identify the issue. It might be good to create a custom exception that can provide more information for these kind of issues.

**Comment by woodp** [comment] 2015-07-30 14:23
I agree it needs to provide more info, workin on it.

I think you could wait for next release or go ahead and clone the repo.

**Comment by johncmckim** [comment] 2015-07-31 11:00
I have identified the issue. The issue occurred on one of our endpoints that returned a SyndicationFeed. I reproduced the bug and added a simple fix. The issue is that the schema variable is empty when a Type has multiple properties and the first property is a Complex Type that does not have settable properties.

I assume this fix is appropriate, please let me know if there is any issues with it.

**Comment by woodp** [comment] 2015-08-05 20:47
fixed in last release

**Closed by woodp** 2015-08-05 20:47 UTC
