### ISSUE TITLE
Arrow, Control and Delete keys stop working after include a RAML Contract

### ISSUE THREAD

**Issue by klaygomes** [mulesoft-labs/raml-dotnet-tools#38] opened 2015-10-16 01:17 UTC
Go to "Add RAML Contract" then choose new RAML contract  after that, when I try to edit any file CTRL, Arrow, Backspace and Delete keys stopping working.

If I try to close Visual Studio it give me this message:
![image](https://cloud.githubusercontent.com/assets/522884/10531586/272055a6-738a-11e5-835d-7ffbf5472ecb.png)

I'm using Visual Studio 2015 Community on Windows 10.

**Comment by tb-wwparker** [comment] 2015-10-21 01:19
This happens to me on a semi-frequent basis. It happens in two spots, the most common is add RAML, but it also happens in Update RAML.
It appears to be caused by a pop-up windows that is asking you if you want to update window contents with the file that was just updated. This happens if you have the generated file open as part of your solution. Sometimes, but I have not quite figured out all of the times, this dialog box does not display (but Visual Studio believes it is and is waiting for you to pick one of the buttons). The only way to fix it is to quit Visual Studio, as it has a modal lock on all keyboard input.

**Comment by woodp** [comment] 2015-10-22 12:36
This happened to me a couple of times. I think the problem is caused by Visual Studio and not the tool. 
Have not found a workaround for this.

**Comment by garethpn** [comment] 2018-03-27 13:56
Has anyone found a fix for this yet?

**Comment by woodp** [comment] 2019-11-22 14:05
I haven't encountered this issue for a long time

**Closed by woodp** 2019-11-22 14:05 UTC
Labels: bug
